
import type { ZodiacSignName } from '@/types';

export interface CompatibilityReportDetail {
  report: string;
  score: number;
}

export const loveCompatibilityPairings: Record<string, CompatibilityReportDetail> = {
  "Aries-Leo": {
    report: "Una pareja poderosa y apasionada, dos fuegos que se alimentan mutuamente. Su conexión es instantánea, llena de energía, admiración y un deseo compartido de liderazgo. El amor es un gran escenario donde ambos disfrutan brillar. Fortalezas: Lealtad inquebrantable, generosidad y una vida social vibrante. Desafíos: El choque de egos es su principal obstáculo. Ambos quieren dominar y pueden competir por el centro de atención. Clave del éxito: Celebrar los logros del otro como propios, aprender a compartir el protagonismo y transformar la competencia en un juego de equipo.",
    score: 5
  },
  "Taurus-Cancer": {
    report: "Una combinación tierna, segura y profundamente hogareña. Tauro ofrece la estabilidad y la sensualidad que Cáncer anhela, mientras que Cáncer aporta el cuidado y la calidez emocional que Tauro valora. Juntos construyen un refugio del mundo, un santuario de amor, buena comida y confort. Fortalezas: Lealtad absoluta, devoción y un entendimiento mutuo sobre la importancia de la seguridad y el hogar. Desafíos: La terquedad de Tauro puede chocar con la hipersensibilidad de Cáncer. Cáncer debe aprender a comunicar sus necesidades sin indirectas, y Tauro a ser más flexible. Clave del éxito: La paciencia y la comunicación afectuosa son fundamentales. Su amor crece con el tiempo, basado en la confianza y el cuidado mutuo.",
    score: 5
  },
  "Gemini-Libra": {
    report: "Una conexión mental chispeante y socialmente elegante. Como signos de Aire, disfrutan de la comunicación, el arte, la belleza y una vida social activa. Se entienden a un nivel intelectual profundo, creando una relación equilibrada y armoniosa. Fortalezas: Gran complicidad intelectual, excelentes conversaciones y un aprecio mutuo por la estética y la vida social. Son una pareja encantadora. Desafíos: Ambos pueden evitar los conflictos y las conversaciones emocionales profundas. La indecisión, tanto de Géminis como de Libra, puede ser un problema a la hora de tomar decisiones importantes. Clave del éxito: Aprender a abordar los problemas emocionales con la misma habilidad con la que discuten ideas y encontrar un compromiso entre la diversión y la responsabilidad.",
    score: 5
  },
  "Virgo-Capricorn": {
    report: "Práctica, leal y orientada al éxito. Dos signos de Tierra que comparten valores similares sobre el trabajo duro, la ambición y la estabilidad. Se apoyan mutuamente en sus objetivos y construyen una vida sólida y bien organizada. El respeto mutuo es inmenso. Fortalezas: Fiabilidad, metas compartidas y un profundo sentido del deber el uno hacia el otro. Son un equipo formidable en la vida y en el trabajo. Desafíos: Pueden caer en una rutina y descuidar el romance y la espontaneidad. Ambos tienden a ser demasiado críticos, consigo mismos y con el otro. Clave del éxito: Programar tiempo para el romance, celebrar los logros y aprender a relajarse y disfrutar de los frutos de su trabajo juntos.",
    score: 5
  },
  "Scorpio-Pisces": {
    report: "Una conexión de alma profunda, intuitiva y casi mágica. Ambos signos de Agua navegan por las profundidades emocionales con facilidad. Hay una comprensión casi psíquica entre ellos, creando un vínculo increíblemente fuerte y transformador. Fortalezas: Empatía profunda, conexión espiritual y una intimidad emocional que pocos logran. Se sienten seguros y comprendidos el uno con el otro. Desafíos: Pueden perderse en su propio mundo emocional y descuidar los aspectos prácticos de la vida. La intensidad de Escorpio a veces puede abrumar al soñador Piscis. Clave del éxito: Mantener un pie en la realidad, equilibrar la ensoñación con la acción y usar su profunda conexión para sanarse y apoyarse mutuamente.",
    score: 5
  },
  "Aries-Taurus": {
    report: "La impulsividad de Aries choca con la necesidad de seguridad y ritmo pausado de Tauro. Es una relación de 'frenar y acelerar'. Fortalezas: Si logran apreciar sus diferencias, la pasión de Aries puede inspirar a Tauro a la acción, mientras que la sensualidad y calma de Tauro puede enseñar a Aries a disfrutar de los placeres de la vida. Desafíos: La paciencia es el mayor desafío. Aries quiere todo ya, y Tauro necesita su tiempo. Sus diferentes ritmos pueden generar frustración. Clave del éxito: Un enorme respeto mutuo por sus diferentes naturalezas. Aries debe aprender a valorar la estabilidad, y Tauro a aceptar un poco de riesgo y aventura.",
    score: 3
  },
  "Cancer-Libra": {
    report: "Cáncer busca seguridad emocional profunda, mientras que Libra busca equilibrio y armonía social. Cáncer puede ver a Libra como demasiado superficial o indeciso, y Libra puede sentirse abrumado por la intensidad emocional de Cáncer. Fortalezas: Ambos valoran las relaciones y el compromiso. Libra puede enseñar a Cáncer a socializar y ver diferentes perspectivas, y Cáncer puede ayudar a Libra a conectar más profundamente con sus emociones. Desafíos: Sus necesidades emocionales son muy diferentes. Cáncer necesita un nido seguro, Libra necesita interacción social. Clave del éxito: La comunicación abierta sobre sus sentimientos y necesidades es vital. Deben encontrar un punto medio entre la vida social y la intimidad del hogar para que ambos se sientan satisfechos.",
    score: 2
  },
  "Leo-Scorpio": {
    report: "Una pareja de voluntades fuertes, magnéticas y extremadamente apasionadas. La intensidad es altísima, pero también el potencial de conflicto por el control y los celos. Ambos son signos fijos y leales, pero muy posesivos. Fortalezas: Una lealtad feroz y una pasión que puede mover montañas. Cuando están en sintonía, son una pareja poderosa e imparable. Desafíos: Las luchas de poder son casi inevitables. Ambos son orgullosos y les cuesta ceder. Los celos pueden ser un problema destructivo. Clave del éxito: La confianza absoluta es innegociable. Deben aprender a canalizar su energía de forma constructiva, admirar las fortalezas del otro y ceder el control de vez en cuando.",
    score: 3
  },
  "Aquarius-Pisces": {
    report: "El desapego mental de Acuario puede herir la sensible naturaleza de Piscis, que necesita conexión emocional. Sin embargo, ambos comparten un profundo idealismo y compasión por la humanidad. Fortalezas: Juntos pueden soñar con un mundo mejor y trabajar por causas humanitarias. Su conexión puede ser muy creativa y espiritual. Desafíos: La necesidad de espacio de Acuario puede hacer que Piscis se sienta abandonado. La lógica de Acuario choca con la intuición de Piscis. Clave del éxito: Acuario debe aprender a validar los sentimientos de Piscis, y Piscis a respetar la necesidad de independencia de Acuario. Conectar a través de sus ideales compartidos puede ser el puente que una sus mundos.",
    score: 3
  },
  "Aries-Libra": {
    report: "La clásica atracción de los opuestos. Aries, el guerrero impulsivo, se siente fascinado por la gracia y diplomacia de Libra. Libra, a su vez, se siente atraído por la pasión y seguridad de Aries. Fortalezas: Se complementan maravillosamente. Aries toma la iniciativa y Libra se encarga de las relaciones y la estrategia. Juntos forman un equipo dinámico y equilibrado. Desafíos: El estilo de comunicación. Aries es directo y confrontacional, mientras que Libra evita el conflicto. Esto puede llevar a resentimientos si los problemas no se abordan. Clave del éxito: Aries debe aprender a ser más diplomático, y Libra a ser más directo y no temer el desacuerdo. La comunicación honesta es su mejor herramienta.",
    score: 4
  },
  "Taurus-Leo": {
    report: "Una pareja de reyes y reinas que aman el lujo, el placer y la estabilidad. Sin embargo, ambos son signos fijos y muy tercos, lo que puede llevar a luchas de poder épicas. Fortalezas: Ambos son extremadamente leales y protectores con su pareja. Disfrutan construyendo una vida cómoda y hermosa juntos. Su amor es sólido y duradero si superan sus diferencias. Desafíos: La terquedad. Ninguno quiere ceder. Leo necesita admiración constante, y Tauro necesita tranquilidad y seguridad, a veces en conflicto con la necesidad de Leo de ser el centro de atención. Clave del éxito: La admiración mutua es clave. Tauro debe ofrecer a Leo el reconocimiento que necesita, y Leo debe valorar la calma y el apoyo incondicional de Tauro.",
    score: 2
  },
  "Gemini-Virgo": {
    report: "Ambos regidos por Mercurio, su conexión es principalmente mental, pero enfocada de manera muy diferente. Géminis es disperso y curioso, mientras que Virgo es analítico y detallista. Fortalezas: Pueden tener conversaciones fascinantes y aprender mucho el uno del otro. Virgo ayuda a Géminis a enfocarse, y Géminis ayuda a Virgo a relajarse y ver múltiples posibilidades. Desafíos: Virgo puede encontrar a Géminis poco fiable o superficial, y Géminis puede ver a Virgo como demasiado crítico y perfeccionista. La ansiedad puede ser un problema para ambos. Clave del éxito: Valorar la perspectiva del otro como un complemento y no como una crítica. La paciencia y el sentido del humor son esenciales.",
    score: 3
  },
  "Cancer-Capricorn": {
    report: "Otra poderosa pareja de opuestos que se complementan a la perfección. Cáncer (hogar, emoción) y Capricornio (carrera, estructura) son las dos caras de la misma moneda. Fortalezas: Cáncer nutre las ambiciones de Capricornio y le proporciona un refugio seguro. Capricornio le da a Cáncer la estabilidad y seguridad que tanto anhela. Juntos, pueden construir un verdadero imperio basado en el amor, la lealtad y el respeto mutuo. Desafíos: Capricornio puede parecer frío o distante para el sensible Cáncer, y Cáncer puede parecer demasiado emocional o dependiente para el pragmático Capricornio. Clave del éxito: Entender que expresan el amor de maneras diferentes. Capricornio lo demuestra con actos y compromiso, Cáncer con afecto y cuidado. Ambos son valiosos.",
    score: 5
  },
  "Leo-Aquarius": {
    report: "El rey y el rebelde. Estos opuestos del zodíaco sienten una fuerte atracción magnética, una mezcla de fascinación y exasperación. Fortalezas: Son una pareja socialmente brillante, creativa y poco convencional. Leo enseña a Acuario a conectar con su corazón y su lado más personal, mientras que Acuario enseña a Leo a ver más allá de sí mismo y a pensar en el colectivo. Desafíos: Sus necesidades son opuestas. Leo busca adoración personal, Acuario busca libertad e igualdad. Leo es cálido y expresivo, Acuario es más distante y mental. Clave del éxito: Respetar sus diferencias fundamentales. Deben encontrar un equilibrio entre la vida social y la personal, y valorar la perspectiva única que cada uno aporta.",
    score: 4
  },
  "Virgo-Pisces": {
    report: "El sanador y el soñador. Estos opuestos se atraen de una manera profundamente espiritual y compasiva. Su conexión es casi mágica. Fortalezas: El potencial para sanarse mutuamente es inmenso. Virgo ayuda a Piscis a materializar sus sueños y a mantenerse anclado, y Piscis ayuda a Virgo a conectar con la fe, la intuición y a ser menos autocrítico. Desafíos: El pragmatismo de Virgo puede chocar con el escapismo de Piscis. Virgo puede volverse demasiado crítico, y Piscis puede sentirse herido o incomprendido. Clave del éxito: La aceptación incondicional. Virgo debe aceptar el mundo de ensueño de Piscis, y Piscis debe apreciar el cuidado práctico de Virgo. Juntos pueden alcanzar un equilibrio perfecto entre lo místico y lo terrenal.",
    score: 4
  },
  "Libra-Scorpio": {
    report: "Una combinación intrigante y compleja. El sociable y armonioso Libra se siente atraído por la misteriosa intensidad de Escorpio. Escorpio, a su vez, se siente cautivado por el encanto y la belleza de Libra. Fortalezas: Ambos son románticos y buscan una conexión profunda. Su vida íntima puede ser muy apasionada. Libra aporta equilibrio social y Escorpio una profundidad emocional inigualable. Desafíos: La necesidad de paz de Libra choca con la tendencia de Escorpio a explorar las profundidades emocionales, incluyendo los celos y el conflicto. Escorpio puede ver a Libra como superficial, y Libra puede temer la intensidad de Escorpio. Clave del éxito: La confianza y la comunicación son vitales. Libra debe aprender a no temer el conflicto sano, y Escorpio a confiar en la lealtad de Libra.",
    score: 3
  },
  "Scorpio-Sagittarius": {
    report: "Agua y Fuego, una combinación de vapor y pasión. Escorpio es profundo, privado e intenso, mientras que Sagitario es abierto, expansivo y amante de la libertad. Fortalezas: La atracción inicial puede ser explosiva. Sagitario saca a Escorpio de su caparazón, y Escorpio ofrece a Sagitario una profundidad que rara vez encuentra. Juntos, pueden vivir grandes aventuras. Desafíos: Sus naturalezas son muy diferentes. La necesidad de libertad de Sagitario puede activar los celos y la posesividad de Escorpio. Escorpio puede encontrar a Sagitario imprudente o superficial. Clave del éxito: Honestidad radical y mucho espacio. Deben respetar sus diferencias fundamentales y encontrar un equilibrio entre la aventura y la intimidad.",
    score: 2
  },
  "Sagittarius-Capricorn": {
    report: "El optimista aventurero se encuentra con el estratega pragmático. Sagitario puede ayudar a Capricornio a relajarse y ver el lado bueno de la vida, mientras que Capricornio puede dar a Sagitario el enfoque y la estructura necesarios para convertir sus grandes ideas en realidad. Fortalezas: Se equilibran bien si están dispuestos a aprender el uno del otro. Son una pareja que puede lograr grandes cosas, combinando visión y ejecución. Desafíos: Sagitario puede ver a Capricornio como demasiado serio o pesimista, y Capricornio puede ver a Sagitario como irresponsable o poco fiable. Clave del éxito: Respetar sus diferentes enfoques de la vida. Deben valorar lo que el otro aporta a la relación y encontrar un terreno común en sus metas a largo plazo.",
    score: 3
  },
  "Aquarius-Taurus": {
    report: "El innovador y el tradicionalista. Ambos son signos fijos, por lo que son tercos y resistentes al cambio, pero de maneras muy diferentes. Fortalezas: Si logran superar sus diferencias, pueden construir una relación increíblemente estable y leal. Tauro puede ofrecer a Acuario un hogar seguro al que volver, y Acuario puede abrir la mente de Tauro a nuevas ideas y posibilidades. Desafíos: Es una cuadratura desafiante. Acuario vive en el futuro y las ideas, mientras que Tauro se aferra a lo tangible y probado. Sus valores fundamentales pueden chocar constantemente. Clave del éxito: Un inmenso respeto por los valores y el espacio del otro. La paciencia es fundamental. Deben encontrar proyectos en común donde puedan combinar sus talentos únicos.",
    score: 2
  },
  "Aries-Sagittarius": {
    report: "Dos almas de fuego unidas por la aventura y el optimismo. Esta pareja comparte un amor insaciable por la libertad, los viajes y las nuevas experiencias. La energía es alta, la risa es constante y rara vez hay un momento aburrido. Fortalezas: Se inspiran mutuamente a ser más audaces y a vivir la vida al máximo. La honestidad brutal de ambos signos crea una base de transparencia, y su energía combinada es magnética y contagiosa. Desafíos: Ambos pueden ser impulsivos y poco tactful, lo que lleva a discusiones explosivas pero generalmente breves. El compromiso a largo plazo puede ser un desafío si no sienten que están creciendo y explorando juntos. Clave del éxito: Canalizar su energía en aventuras compartidas, darse mutuamente el espacio que necesitan para ser independientes y aprender a comunicarse con un poco más de suavidad.",
    score: 5
  },
  "Taurus-Virgo": {
    report: "Una unión terrenal basada en la lealtad, la practicidad y un profundo respeto mutuo. Ambos anhelan seguridad y estabilidad, y trabajan juntos de manera eficiente para construir una vida cómoda y bien organizada. Es una relación que se siente segura y predecible de la mejor manera posible. Fortalezas: Son increíblemente fiables y devotos el uno al otro. Virgo aprecia la sensualidad y la calma de Tauro, mientras que Tauro admira la inteligencia y la dedicación de Virgo. Juntos, crean un santuario de paz. Desafíos: La relación puede volverse demasiado rutinaria o predecible, olvidando el romance. Virgo puede ser demasiado crítico con el hedonista Tauro, y Tauro puede ver a Virgo como demasiado ansioso. Clave del éxito: Hacer un esfuerzo consciente por incorporar el romance y la espontaneidad. Virgo debe suavizar sus críticas y Tauro debe apreciar el deseo de Virgo de mejorar las cosas.",
    score: 5
  },
  "Gemini-Aquarius": {
    report: "Una conexión mental instantánea y electrizante. Como dos signos de aire, su relación se basa en la comunicación, las ideas innovadoras y una necesidad compartida de libertad e independencia. Son mejores amigos y amantes, explorando el mundo de las ideas juntos. Fortalezas: Complicidad intelectual inigualable. Nunca se quedan sin cosas de qué hablar. Ambos son sociales, curiosos y abiertos a probar cosas nuevas, lo que mantiene la relación fresca y emocionante. Desafíos: Pueden tener dificultades para conectar a un nivel emocional profundo, prefiriendo racionalizar los sentimientos. Su naturaleza impredecible puede hacer que la estabilidad a largo plazo sea un desafío si no se trabaja conscientemente. Clave del éxito: Fomentar la intimidad emocional además de la intelectual. Apoyar la individualidad del otro mientras se construyen metas compartidas que los unan.",
    score: 5
  },
  "Cancer-Scorpio": {
    report: "Una de las conexiones más profundas e intensas del zodíaco. Ambos signos de agua operan a un nivel emocional e intuitivo que otros raramente comprenden. Es una relación de 'todo o nada', llena de pasión, lealtad y un vínculo casi psíquico. Fortalezas: Lealtad y devoción feroces. Crean un espacio emocional increíblemente seguro donde ambos pueden ser vulnerables. La comprensión mutua es profunda y a menudo no necesita palabras. Desafíos: La intensidad combinada puede llevar a estados de ánimo turbulentos y celos. Ambos pueden ser posesivos y manipuladores si se sienten inseguros. Tienden a guardar rencor. Clave del éxito: La confianza total y la honestidad son cruciales. Deben aprender a perdonar y a comunicar sus miedos en lugar de actuar sobre ellos. Su profunda conexión puede ser transformadora si se usa para sanar.",
    score: 5
  },
  "Libra-Sagittarius": {
    report: "Una pareja optimista, social y amante de la diversión. La diplomacia y el encanto de Libra se combinan con el espíritu aventurero y filosófico de Sagitario. Disfrutan de una vida social activa, viajes y conversaciones estimulantes. Fortalezas: Se lo pasan genial juntos. Mantienen una perspectiva positiva de la vida y se animan mutuamente a crecer. Sagitario ayuda a Libra a ser más decidido, y Libra ayuda a Sagitario a ser un poco más refinado. Desafíos: La franqueza de Sagitario puede herir la sensibilidad de Libra, que evita el conflicto. La indecisión de Libra puede frustrar al impaciente Sagitario. El compromiso puede ser un tema delicado para ambos. Clave del éxito: Comunicación abierta sobre las expectativas. Libra debe aprender a no tomarse la honestidad de Sagitario como algo personal, y Sagitario debe desarrollar un poco más de tacto.",
    score: 4
  },
  "Aries-Aries": {
    report: "Cuando dos Aries se unen, el mundo debe prepararse para una explosión de energía, pasión y competencia. Esta es una relación de alta intensidad, donde ambos se entienden a la perfección en su necesidad de acción y liderazgo. Son compañeros de aventura ideales, siempre empujándose mutuamente a ser más audaces. Fortalezas: Una comprensión innata del otro, una pasión compartida por la vida y una energía inagotable que los convierte en una pareja dinámica. La honestidad es brutal y directa, sin juegos. Desafíos: El principal problema es quién manda. Dos líderes naturales pueden chocar constantemente por el control. Su impaciencia y temperamento pueden llevar a discusiones explosivas y frecuentes. Clave del éxito: Aprender a ser un equipo en lugar de competidores. Deben canalizar su energía competitiva hacia metas externas, celebrar los éxitos del otro y practicar la paciencia, dándose espacio para respirar.",
    score: 4
  },
  "Taurus-Libra": {
    report: "Ambos regidos por Venus, el planeta del amor y la belleza, esta pareja comparte un aprecio por las cosas buenas de la vida. Sin embargo, lo expresan de manera diferente: Tauro (Tierra) a través de la sensualidad y el confort material, y Libra (Aire) a través de la armonía social y la estética intelectual. Fortalezas: Su hogar será un templo de belleza y buen gusto. Ambos son románticos y buscan una relación estable y comprometida. Tauro ofrece la estabilidad que Libra necesita, y Libra aporta el encanto y la diplomacia que suavizan la terquedad de Tauro. Desafíos: La indecisión de Libra puede frustrar al práctico Tauro. Tauro es hogareño, mientras que Libra necesita una vida social activa, lo que puede generar conflictos. Libra puede encontrar a Tauro demasiado posesivo. Clave del éxito: El compromiso es la palabra clave. Deben encontrar un equilibrio entre la vida social y la tranquilidad del hogar. La comunicación abierta sobre sus necesidades y un aprecio genuino por la perspectiva del otro los mantendrá unidos.",
    score: 4
  },
  "Gemini-Cancer": {
    report: "Una combinación del intelecto y la emoción, donde la mente curiosa de Géminis se encuentra con el corazón sensible de Cáncer. Géminis se siente atraído por la naturaleza cariñosa de Cáncer, y Cáncer se fascina con la agilidad mental de Géminis. Fortalezas: Géminis puede ayudar a Cáncer a expresar sus sentimientos con palabras, mientras que Cáncer puede enseñar a Géminis a conectar con sus propias emociones. Su relación puede estar llena de conversaciones interesantes y cuidado tierno. Desafíos: El núcleo del problema es la seguridad. Cáncer necesita seguridad emocional constante, mientras que Géminis necesita libertad y variedad, lo que puede hacer que Cáncer se sienta inseguro. La naturaleza cambiante de Géminis puede ser confusa para el hogareño Cáncer. Clave del éxito: Géminis debe hacer un esfuerzo consciente por ofrecer seguridad y ser sensible a los estados de ánimo de Cáncer. Cáncer debe aprender a dar a Géminis el espacio que necesita y a no tomar su necesidad de estímulo mental como algo personal.",
    score: 2
  },
  "Leo-Virgo": {
    report: "El rey del zodíaco se encuentra con el perfeccionista. Leo, extravagante y amante del protagonismo, choca con el práctico y reservado Virgo. Sin embargo, pueden complementarse de maneras sorprendentes si se lo proponen. Fortalezas: Virgo puede ser el apoyo práctico y organizador que Leo necesita para brillar, gestionando los detalles detrás de escena. Leo, a su vez, puede ayudar a Virgo a salir de su caparazón, a ser más seguro y a disfrutar más de la vida. Desafíos: La crítica constructiva de Virgo puede sonar a juicio personal para el orgulloso Leo. La necesidad de atención de Leo puede parecer frívola para el servicial Virgo. Sus enfoques de la vida son fundamentalmente diferentes. Clave del éxito: La apreciación mutua. Leo debe valorar el servicio y la inteligencia de Virgo, y Virgo debe aprender a expresar su admiración por la calidez y generosidad de Leo. Encontrar un equilibrio entre el trabajo y el juego es esencial.",
    score: 3
  },
  "Sagittarius-Pisces": {
    report: "El filósofo se encuentra con el místico. Ambos regidos tradicionalmente por Júpiter, comparten una búsqueda de significado más allá de lo mundano. Sagitario busca la verdad a través de la aventura y el conocimiento, mientras que Piscis la busca a través de la conexión espiritual y la empatía. Fortalezas: Su conexión puede ser profundamente espiritual y expansiva. Ambos son compasivos y de mente abierta, lo que les permite aceptar sus excentricidades. Pueden inspirarse mutuamente a soñar en grande. Desafíos: La honestidad directa de Sagitario puede herir profundamente al sensible Piscis. Piscis necesita intimidad emocional, mientras que Sagitario necesita libertad sin ataduras, lo que puede generar malentendidos. Sagitario vive en el mundo, Piscis en sus sueños. Clave del éxito: Sagitario debe aprender a ser más delicado con sus palabras, y Piscis debe desarrollar una piel un poco más gruesa y respetar la necesidad de independencia de Sagitario. Conectar a través de sus intereses espirituales y filosóficos puede ser su mayor fortaleza.",
    score: 3
  },
  "Aries-Virgo": {
    report: "El impulso de Aries se encuentra con el análisis de Virgo. Es una combinación de 'actuar ahora' versus 'planificar primero'. Pueden aprender mucho el uno del otro si logran superar sus diferencias fundamentales de ritmo y enfoque. Fortalezas: Aries aporta la energía para iniciar proyectos, mientras que Virgo aporta la habilidad para perfeccionarlos y llevarlos a buen término. Juntos, pueden ser increíblemente productivos. Desafíos: La impaciencia de Aries puede estresar al meticuloso Virgo, quien puede parecer demasiado crítico y lento para el carnero. Virgo necesita orden y rutina, mientras que Aries vive de la espontaneidad. Clave del éxito: La paciencia y la comunicación son fundamentales. Aries debe aprender a valorar la planificación, y Virgo debe aprender a relajarse y no tomar el impulso de Aries como una falta de cuidado.",
    score: 2
  },
  "Taurus-Sagittarius": {
    report: "El hogareño y amante del confort Tauro se encuentra con el aventurero y errante Sagitario. Sus valores y estilos de vida son casi opuestos, lo que hace de esta una relación desafiante que requiere un gran compromiso. Fortalezas: Sagitario puede sacar a Tauro de su zona de confort y mostrarle el mundo, mientras que Tauro puede ofrecer a Sagitario un puerto seguro. Desafíos: La necesidad de libertad de Sagitario choca directamente con la necesidad de seguridad y posesividad de Tauro. Pueden surgir problemas de dinero y compromiso. Clave del éxito: Encontrar un equilibrio entre la aventura y la vida hogareña. Deben tener intereses comunes y un profundo respeto por las necesidades del otro. Tauro debe dar espacio, y Sagitario debe demostrar fiabilidad.",
    score: 2
  },
  "Gemini-Leo": {
    report: "Una pareja social, carismática y llena de diversión. La mente brillante de Géminis se combina a la perfección con la calidez y el deseo de ser el centro de atención de Leo. Juntos, son el alma de la fiesta. Fortalezas: La admiración es mutua. Su vida social es vibrante y su comunicación es excelente, llena de risas y juegos. Desafíos: El ego de Leo puede chocar con la necesidad de Géminis de flirtear con todo el mundo. Leo puede sentirse herido por la naturaleza a veces distante de Géminis. Clave del éxito: Géminis debe asegurarse de que Leo se sienta especial. Leo debe comprender la necesidad de Géminis de estímulo mental y variedad social sin tomarlo como algo personal.",
    score: 4
  },
  "Cancer-Leo": {
    report: "El rey/reina se encuentra con el cuidador del reino. Cáncer anhela seguridad emocional, mientras que Leo desea admiración y un escenario para brillar. Pueden ofrecerse mutuamente lo que más desean si superan sus diferencias. Fortalezas: Leo ofrece una lealtad feroz que hace que Cáncer se sienta seguro. Cáncer, a su vez, adora y cuida a Leo, satisfaciendo su necesidad de atención. Desafíos: El orgullo de Leo puede chocar con la sensibilidad de Cáncer. Un comentario descuidado de Leo puede herir profundamente a Cáncer. Clave del éxito: Leo debe aprender a ser sensible a los estados de ánimo de Cáncer. Cáncer debe aprender a expresar sus necesidades directamente y a compartir a su rey/reina con el mundo.",
    score: 4
  },
  "Scorpio-Aquarius": {
    report: "Una combinación de dos signos fijos increíblemente poderosos y tercos, pero con enfoques de vida radicalmente diferentes. Escorpio es profundo y emocional, mientras que Acuario es mental y desapegado. Es una relación magnética pero altamente desafiante. Fortalezas: Ambos son inteligentes y curiosos. Pueden tener conversaciones fascinantes sobre los misterios de la vida. Si logran unirse, pueden ser una fuerza formidable para el cambio. Desafíos: La necesidad de fusión emocional de Escorpio choca con la necesidad de independencia de Acuario. Escorpio puede ver a Acuario como frío, y Acuario puede sentirse sofocado por las demandas emocionales de Escorpio. Clave del éxito: Un respeto radical por la individualidad del otro. Deben encontrar un propósito común más grande que ellos mismos. Escorpio debe aprender a confiar, y Acuario a conectarse emocionalmente.",
    score: 2
  },
  "Aries-Gemini": {
    report: "Fuego y Aire se combinan en una relación llena de energía, diversión y estímulo intelectual. La curiosidad insaciable de Géminis mantiene entretenido al aventurero Aries. Nunca se aburren y su vida social es vibrante. Fortalezas: Comunicación constante, amor por la novedad, y una energía juvenil que mantiene la relación fresca. Ambos son independientes y respetan el espacio del otro. Desafíos: La falta de profundidad emocional puede ser un problema. Aries es pasional, mientras que Géminis es más mental. La inconstancia de Géminis puede chocar con la necesidad de Aries de ser el centro de atención. Clave del éxito: Canalizar su energía en proyectos creativos juntos. Aries debe aprender a no tomarse la naturaleza coqueta de Géminis como algo personal, y Géminis debe ofrecerle a Aries la atención y la emoción que necesita.",
    score: 4
  },
  "Aries-Cancer": {
    report: "Una combinación desafiante de Fuego y Agua. La naturaleza directa y a veces brusca de Aries puede herir fácilmente al sensible Cáncer. Sin embargo, si logran entenderse, pueden protegerse mutuamente con ferocidad. Fortalezas: Aries aporta pasión y empuje, sacando a Cáncer de su caparazón. Cáncer ofrece un cuidado y una lealtad que pueden calmar el alma inquieta de Aries, creando un hogar al que siempre querrá volver. Desafíos: Sus necesidades son opuestas. Aries necesita acción y libertad; Cáncer necesita seguridad y conexión emocional. Los estados de ánimo de Cáncer pueden confundir a Aries, y la impulsividad de Aries puede hacer que Cáncer se sienta inseguro. Clave del éxito: Aries debe cultivar la gentileza y la protección, convirtiéndose en el caballero de brillante armadura de Cáncer. Cáncer debe aprender a establecer límites saludables y a no tomar la naturaleza de Aries como un ataque personal. La empatía es la clave.",
    score: 2
  },
  "Aries-Scorpio": {
    report: "Dos signos regidos por Marte. La pasión aquí es volcánica, magnética e intensa. Ambos son guerreros, lo que puede llevar a una lealtad inquebrantable o a batallas épicas por el poder. Fortalezas: Una conexión física y emocional increíblemente profunda. Ambos son valientes, decididos y se admiran mutuamente por su fuerza. Cuando están unidos, son una fuerza imparable. Desafíos: El control es el gran tema. Ambos quieren liderar y son extremadamente posesivos. Los celos y la desconfianza pueden envenenar la relación si no se manejan con cuidado. Clave del éxito: Transparencia total y confianza absoluta. Deben aprender a luchar juntos contra el mundo, no entre ellos. Canalizar su intensidad compartida en metas comunes es esencial para su supervivencia.",
    score: 3
  },
  "Aries-Capricorn": {
    report: "El impulso contra la estrategia. Aries corre hacia adelante, mientras que Capricornio construye pacientemente. Esta es una relación de 'maestro y aprendiz' en ambos sentidos, pero puede generar mucha fricción. Fortalezas: Si logran alinear sus metas, son imparables. Aries proporciona la chispa y la energía, y Capricornio la estructura y la disciplina para triunfar. Ambos son ambiciosos y respetan el éxito. Desafíos: Sus ritmos son opuestos. Aries puede ver a Capricornio como lento y aburrido, mientras que Capricornio puede ver a Aries como imprudente e inmaduro. La necesidad de Aries de gratificación instantánea choca con la visión a largo plazo de Capricornio. Clave del éxito: Aprender a valorar las fortalezas del otro. Aries debe respetar la sabiduría y la planificación de Capricornio, y Capricornio debe admirar el coraje y la iniciativa de Aries. La paciencia es una virtud que ambos deben cultivar.",
    score: 2
  },
  "Aries-Aquarius": {
    report: "Una combinación emocionante y poco convencional. El espíritu pionero de Aries se siente atraído por la originalidad y la visión de futuro de Acuario. Ambos son independientes y aman la libertad. Fortalezas: Son grandes amigos además de amantes. Se dan mutuamente el espacio que necesitan para prosperar. Su relación está llena de ideas nuevas, proyectos sociales y aventuras espontáneas. Desafíos: La conexión emocional puede ser un punto débil. Aries es pasional y personal, mientras que Acuario tiende a ser más desapegado y mental, enfocado en el colectivo. Aries puede sentirse poco especial. Clave del éxito: Celebrar su individualidad y trabajar juntos en causas que les apasionen. Aries debe entender que el amor de Acuario es menos demostrativo pero genuino, y Acuario debe hacer un esfuerzo por conectar con el lado más cálido y personal de Aries.",
    score: 4
  },
  "Aries-Pisces": {
    report: "Fuego y Agua en una unión delicada y a menudo confusa. La fuerza y la franqueza de Aries pueden abrumar al soñador y sensible Piscis. Sin embargo, hay una fascinación mutua: el guerrero y el místico. Fortalezas: Aries puede proteger a Piscis e inspirarle a actuar sobre sus sueños. Piscis puede enseñar a Aries sobre la compasión, la empatía y la belleza de rendirse al flujo de la vida. La conexión puede ser muy romántica y creativa. Desafíos: La impulsividad de Aries puede herir a Piscis sin quererlo. La tendencia de Piscis al escapismo puede frustrar al realista Aries. Pueden operar en frecuencias completamente diferentes. Clave del éxito: Aries debe cultivar la gentileza y la protección, convirtiéndose en el caballero de brillante armadura de Piscis. Piscis debe aprender a establecer límites saludables y a no tomar la naturaleza de Aries como un ataque personal. La empatía es la clave.",
    score: 2
  },
  "Taurus-Taurus": {
    report: "Cuando dos Tauro se unen, crean un paraíso de confort, sensualidad y estabilidad. Esta es una relación basada en valores compartidos: amor por la seguridad, los placeres de la vida y una lealtad inquebrantable. Se entienden instintivamente y construyen juntos una vida predecible y hermosa, un refugio seguro contra el caos del mundo. Fortalezas: Lealtad absoluta, una profunda conexión sensual y física, y un enfoque práctico y unificado hacia las metas financieras y de vida. Son un equipo sólido que valora la tradición y la fiabilidad. Desafíos: La terquedad es su mayor enemigo, multiplicada por dos. Si ambos se atrincheran en sus posturas, pueden llegar a un punto muerto del que es difícil salir. La relación corre el riesgo de caer en una rutina cómoda pero aburrida, perdiendo la chispa. Clave del éxito: Aprender a ceder y a ser flexibles es fundamental. Deben hacer un esfuerzo consciente por introducir variedad y espontaneidad en su vida, probar nuevos restaurantes, viajar a nuevos lugares y mantener viva la llama del romance.",
    score: 4
  },
  "Taurus-Gemini": {
    report: "El Toro terrenal se encuentra con los Gemelos aéreos. Tauro busca estabilidad y rutina, mientras que Géminis anhela variedad y estímulo mental. Esta pareja puede funcionar si ambos aprecian lo que el otro aporta: Géminis puede sacar a Tauro de su zona de confort, y Tauro puede ofrecer a Géminis un ancla de calma y seguridad. Fortalezas: Géminis introduce diversión y novedad en la vida de Tauro. Tauro proporciona la lealtad y el apoyo constante que Géminis necesita secretamente para no sentirse perdido en su propio torbellino de ideas. Desafíos: Sus ritmos y necesidades son opuestos. Tauro puede ver a Géminis como poco fiable o superficial, y Géminis puede sentirse sofocado por la naturaleza posesiva y la necesidad de rutina de Tauro. La comunicación puede ser un problema, ya que Tauro es directo y Géminis es más evasivo. Clave del éxito: La paciencia es la clave. Tauro debe dar a Géminis la libertad social y mental que necesita, y Géminis debe hacer un esfuerzo por demostrar fiabilidad y pasar tiempo de calidad en casa. Encontrar actividades que combinen lo práctico con lo divertido puede unir sus mundos.",
    score: 2
  },
  "Taurus-Scorpio": {
    report: "Una atracción magnética e intensa entre opuestos del zodíaco. La sensualidad terrenal de Tauro se encuentra con la profundidad emocional y la pasión de Escorpio. Es una relación de todo o nada, donde la lealtad y la posesividad son temas centrales. Juntos, pueden alcanzar una intimidad inigualable o enzarzarse en batallas de voluntades épicas. Fortalezas: Una conexión física y emocional increíblemente profunda. Ambos son extremadamente leales y protectores. Tauro ofrece la estabilidad que calma la intensidad de Escorpio, y Escorpio aporta una pasión que despierta el alma de Tauro. Desafíos: La terquedad de ambos puede llevar a conflictos de poder monumentales. Los celos y la posesividad son un riesgo real por ambas partes. Escorpio necesita explorar las profundidades emocionales, mientras que Tauro prefiere la paz y la tranquilidad, lo que puede generar tensión. Clave del éxito: La confianza total y la honestidad son innegociables. Deben aprender a canalizar su intensidad compartida de forma constructiva. Tauro debe estar dispuesto a explorar las emociones, y Escorpio debe aprender a valorar la calma y la seguridad que Tauro ofrece.",
    score: 5
  },
  "Taurus-Pisces": {
    report: "Una unión tierna, romántica y profundamente compasiva. La naturaleza práctica y protectora de Tauro ofrece el ancla segura que el soñador Piscis necesita para navegar por el mundo. A su vez, Piscis aporta magia, creatividad y una profunda conexión espiritual a la vida de Tauro. Fortalezas: Tauro ayuda a Piscis a materializar sus sueños, mientras que Piscis ayuda a Tauro a conectar con su lado más suave e intuitivo. Ambos valoran la belleza, el arte y la tranquilidad, creando un hogar lleno de amor y creatividad. Desafíos: El pragmatismo de Tauro a veces puede chocar con la tendencia de Piscis a evadir la realidad. Tauro puede frustrarse si Piscis no es práctico, y Piscis puede sentirse herido si Tauro no valida sus sentimientos y su mundo de ensueño. Clave del éxito: Tauro debe aprender a ser el protector de los sueños de Piscis, ofreciendo apoyo sin juzgar. Piscis debe apreciar los esfuerzos prácticos de Tauro como una forma de amor. Juntos, pueden crear un equilibrio perfecto entre el mundo material y el espiritual.",
    score: 4
  },
  "Gemini-Gemini": {
    report: "Dos Géminis juntos son sinónimo de diversión, conversación incesante y una vida social vibrante. Se entienden perfectamente en su necesidad de cambio, estímulo mental y variedad. La relación es como una fiesta interminable de ideas y risas. Fortalezas: Una conexión intelectual brillante. Nunca se aburren y siempre están aprendiendo algo nuevo. Ambos son flexibles y adaptables, lo que facilita la superación de pequeños obstáculos. Desafíos: La estabilidad emocional es el gran reto. Ambos pueden ser inconsistentes y evitar las conversaciones emocionales profundas. La falta de un ancla puede hacer que la relación se sienta superficial o que se desvíe sin rumbo. Clave del éxito: Hacer un esfuerzo consciente por construir una base emocional sólida. Deben crear rutinas juntos (sin que se sientan como una cárcel) y comprometerse a hablar de sus sentimientos, no solo de sus ideas. La honestidad sobre su necesidad de espacio es crucial.",
    score: 4
  },
  "Gemini-Scorpio": {
    report: "Una combinación magnética pero muy desafiante. La ligereza y curiosidad de Géminis se enfrentan a la intensidad y profundidad emocional de Escorpio. Géminis quiere explorar la superficie de muchos temas, mientras que Escorpio quiere sumergirse hasta el fondo de uno solo. Fortalezas: La atracción inicial es poderosa. Géminis se siente fascinado por el misterio de Escorpio, y Escorpio se siente intrigado por la agilidad mental de Géminis. Pueden aprender mucho el uno del otro si superan sus diferencias. Desafíos: La desconfianza. La naturaleza social y coqueta de Géminis puede activar los celos de Escorpio. Géminis puede ver a Escorpio como demasiado posesivo y controlador, mientras que Escorpio puede ver a Géminis como superficial e poco fiable. Clave del éxito: Una comunicación brutalmente honesta y el establecimiento de límites claros. Géminis debe entender la necesidad de seguridad de Escorpio, y Escorpio debe dar a Géminis el espacio y la libertad mental que necesita.",
    score: 2
  },
  "Gemini-Sagittarius": {
    report: "La pareja de los opuestos complementarios. Ambos son los viajeros y filósofos del zodíaco, amantes de la libertad, el conocimiento y la aventura. Su conexión es instantánea, llena de optimismo, humor y una sed compartida por la experiencia. Fortalezas: Son los mejores amigos y amantes. Se entienden en su necesidad mutua de independencia y espacio. Su vida juntos es una aventura constante, llena de viajes, aprendizaje y risas. Desafíos: El compromiso puede ser un tema complicado. Ambos temen sentirse atrapados. La comunicación, aunque abundante, puede carecer de profundidad emocional. La honestidad brutal de Sagitario a veces puede chocar con la tendencia de Géminis a jugar con las palabras. Clave del éxito: Encontrar un equilibrio entre la libertad individual y las metas compartidas. Deben asegurarse de que su aventura tenga un propósito común. Trabajar en la intimidad emocional fortalecerá su vínculo más allá de la amistad.",
    score: 4
  },
  "Gemini-Capricorn": {
    report: "El mariposón social se encuentra con la roca sólida. Géminis (Aire) es adaptable, curioso y juguetón, mientras que Capricornio (Tierra) es estructurado, ambicioso y serio. Es una combinación que requiere mucho trabajo y paciencia. Fortalezas: Capricornio puede proporcionar la estabilidad y el enfoque que a menudo le faltan a Géminis, ayudándole a materializar sus ideas. Géminis, a su vez, puede ayudar a Capricornio a relajarse, a socializar y a ver la vida con más ligereza y humor. Desafíos: Sus ritmos y prioridades son muy diferentes. Capricornio puede ver a Géminis como inmaduro y poco fiable, mientras que Géminis puede encontrar a Capricornio aburrido y restrictivo. Clave del éxito: El respeto mutuo por sus diferentes estilos de vida. Deben aprender a valorar lo que el otro aporta. Géminis debe apreciar la seguridad que ofrece Capricornio, y Capricornio debe aprender a disfrutar de la espontaneidad que Géminis trae a su vida.",
    score: 2
  },
  "Gemini-Pisces": {
    report: "Dos almas mutables y adaptables, pero que operan en dimensiones diferentes. Géminis (Aire) es lógico y comunicativo, mientras que Piscis (Agua) es intuitivo y emocional. Esta es una relación de espejos y humo, donde la realidad puede ser difícil de definir. Fortalezas: Ambos son increíblemente creativos, imaginativos y de mente abierta. Pueden construir un mundo de ensueño juntos, lleno de arte, música y fantasía. Su conexión puede ser muy espiritual. Desafíos: La comunicación es un campo minado. Géminis procesa todo con la mente, Piscis con el corazón. Los malentendidos son frecuentes. La necesidad de claridad de Géminis choca con la naturaleza evasiva de Piscis. Clave del éxito: La compasión y la empatía son esenciales. Géminis debe aprender a ser sensible a los sentimientos de Piscis y a no invalidarlos con lógica. Piscis debe esforzarse por comunicar sus emociones de manera más clara. Encontrar un proyecto creativo común puede ser su mejor punto de unión.",
    score: 2
  },
  "Cancer-Cancer": {
    report: "Dos Cáncer juntos crean un océano de emociones, un hogar increíblemente seguro y un profundo entendimiento mutuo. Es una relación basada en el cuidado, la nutrición y la necesidad compartida de seguridad. Se sienten 'en casa' el uno con el otro de una manera que pocos otros signos pueden ofrecer. Fortalezas: Una conexión empática y casi telepática. Se entienden sin palabras y saben instintivamente cómo cuidarse mutuamente. Comparten un amor profundo por la familia, el hogar y las tradiciones. Desafíos: El principal peligro es ahogarse en sus propias emociones. Cuando uno está de mal humor, puede arrastrar al otro. Pueden volverse demasiado introvertidos, aislándose del mundo exterior, y la codependencia es un riesgo real. Clave del éxito: Deben aprender a darse espacio para procesar sus emociones individualmente y a no tomar los estados de ánimo del otro como algo personal. Fomentar amistades y actividades fuera de la pareja es vital para mantener un equilibrio saludable.",
    score: 4
  },
  "Cancer-Virgo": {
    report: "Una unión de cuidado y devoción. La naturaleza práctica y servicial de Virgo encuentra un propósito en cuidar del sensible Cáncer. A su vez, la calidez y el afecto de Cáncer ayudan a Virgo a relajarse y a ser menos autocrítico. Es una relación que se siente segura, estable y llena de actos de amor cotidianos. Fortalezas: Son un equipo increíblemente solidario. Cáncer ofrece el apoyo emocional que Virgo necesita para calmar su ansiedad, y Virgo proporciona la estabilidad y el orden que Cáncer anhela. Ambos son leales y comprometidos. Desafíos: La crítica de Virgo, aunque bien intencionada, puede herir profundamente al susceptible Cáncer. Los cambios de humor de Cáncer pueden desconcertar al lógico Virgo, que intenta 'arreglar' los sentimientos en lugar de simplemente sentirlos. Clave del éxito: Virgo debe aprender a expresar sus observaciones con más tacto y aprecio. Cáncer debe entender que los actos de servicio de Virgo son su lenguaje de amor. La comunicación abierta sobre las necesidades emocionales es fundamental.",
    score: 4
  },
  "Cancer-Sagittarius": {
    report: "El hogareño se encuentra con el explorador. Cáncer anhela la seguridad de un nido, mientras que Sagitario necesita la libertad de los cielos abiertos. Esta es una combinación desafiante que requiere una enorme cantidad de comprensión y compromiso. Fortalezas: Sagitario puede sacar a Cáncer de su caparazón y mostrarle un mundo de aventuras y optimismo. Cáncer puede ofrecer a Sagitario un puerto seguro y un amor incondicional al que siempre puede volver. Desafíos: Sus necesidades fundamentales chocan. La franqueza brutal de Sagitario puede herir profundamente a Cáncer. La necesidad de seguridad de Cáncer puede sentirse como una jaula para el independiente Sagitario. Clave del éxito: Un respeto profundo por sus diferencias. Deben encontrar un equilibrio entre la aventura y el hogar. Cáncer necesita confiar y dar espacio, y Sagitario debe aprender a ser más sensible y a demostrar su compromiso de manera tangible.",
    score: 2
  },
  "Cancer-Aquarius": {
    report: "El corazón y la mente. Cáncer es todo emoción, intuición y conexión personal. Acuario es todo lógica, innovación y conexión universal. Su forma de ver el mundo es tan diferente que la fascinación inicial puede convertirse rápidamente en confusión. Fortalezas: Ambos tienen un lado humanitario, aunque lo expresen de forma diferente. Acuario puede ayudar a Cáncer a ver las cosas desde una perspectiva más objetiva, y Cáncer puede enseñar a Acuario a conectar con sus propias emociones. Desafíos: La necesidad de intimidad emocional de Cáncer choca con el desapego natural de Acuario. Cáncer puede sentirse desatendido emocionalmente, mientras que Acuario puede sentirse sofocado por las demandas emocionales de Cáncer. Clave del éxito: Paciencia y traducción emocional. Acuario debe hacer un esfuerzo consciente por ofrecer calidez y seguridad, mientras que Cáncer debe respetar la necesidad de Acuario de libertad, espacio y amistades diversas. Deben encontrar proyectos comunes donde puedan combinar el corazón y la mente.",
    score: 2
  },
  "Cancer-Pisces": {
    report: "Un sueño romántico hecho realidad. Dos signos de Agua que se fusionan en un océano de empatía, creatividad y conexión espiritual. Se entienden a un nivel profundo e intuitivo, creando un vínculo que se siente predestinado. Es una de las combinaciones más compasivas y tiernas del zodíaco. Fortalezas: Una comprensión emocional casi telepática. Ambos son increíblemente románticos, cariñosos y solidarios. Crean un mundo mágico propio, lleno de arte, música y sueños compartidos. Desafíos: El mayor riesgo es perderse en su propio mar de emociones y evadir las responsabilidades prácticas de la vida. Ambos pueden ser propensos al mal humor y a la pasividad, esperando que el otro resuelva los problemas. Clave del éxito: Deben ayudarse mutuamente a mantener al menos un pie en la tierra. Establecer rutinas prácticas y fomentar la comunicación directa (en lugar de suposiciones) les ayudará a construir un amor que no solo es mágico, sino también duradero.",
    score: 5
  },
  "Leo-Leo": {
    report: "La realeza se encuentra con la realeza. Cuando dos Leo se unen, el resultado es una explosión de carisma, generosidad y drama. Esta es una pareja que ama ser el centro de atención, vivir a lo grande y colmarse mutuamente de afecto y regalos. Fortalezas: Una lealtad y protección feroces. Se admiran y entienden mutuamente su necesidad de reconocimiento. Juntos, son una pareja poderosa, glamurosa y socialmente magnética. Desafíos: La batalla de egos es su mayor obstáculo. ¿Quién tiene la razón? ¿Quién brilla más? La competencia por el protagonismo puede ser agotadora y llevar a conflictos dramáticos. Ambos son orgullosos y les cuesta pedir perdón. Clave del éxito: Aprender a compartir el trono. Deben funcionar como una 'power couple', celebrando los éxitos del otro como si fueran propios. Canalizar su energía creativa en proyectos conjuntos y aprender a reírse de su propio drama es esencial.",
    score: 4
  },
  "Leo-Capricorn": {
    report: "El artista se encuentra con el director general. Leo, extravagante y expresivo, se siente atraído por la solidez y la ambición de Capricornio. Capricornio, a su vez, puede sentirse fascinado por la calidez y la vitalidad de Leo. Es una unión desafiante pero potencialmente muy exitosa. Fortalezas: Leo puede enseñar a Capricornio a disfrutar más de la vida, a relajarse y a conectar con su lado más lúdico. Capricornio puede proporcionar a Leo la estructura, el enfoque y el apoyo práctico para convertir sus sueños en realidad. Ambos son extremadamente leales. Desafíos: Sus prioridades chocan. Leo busca placer y reconocimiento en el presente, mientras que Capricornio se enfoca en el trabajo y las metas a largo plazo. Leo puede ver a Capricornio como aburrido o pesimista, y Capricornio puede ver a Leo como superficial o derrochador. Clave del éxito: Un profundo respeto por sus diferentes estilos de vida. Deben valorar lo que el otro aporta. Leo debe admirar la disciplina de Capricornio, y Capricornio debe aprender a expresar su aprecio por la generosidad y el corazón de Leo.",
    score: 3
  },
  "Leo-Pisces": {
    report: "Una combinación de cuento de hadas: el rey y el soñador. Leo, el león protector, se siente atraído por la naturaleza mística, gentil y compasiva de Piscis. Piscis, a su vez, admira la fuerza, la confianza y la calidez de Leo. Fortalezas: Es una relación increíblemente romántica y creativa. Leo se convierte en el protector de los sueños de Piscis, dándole la confianza para brillar. Piscis ofrece a Leo una adoración y una conexión emocional profunda que satisface su corazón. Desafíos: La franqueza de Leo puede herir sin querer al ultra sensible Piscis. La tendencia de Piscis a evadir la realidad puede frustrar al directo Leo. Leo necesita ser el centro de atención, mientras que Piscis necesita retirarse a su mundo interior. Clave del éxito: La comunicación delicada es vital. Leo debe aprender a ser un líder gentil y protector, no un dictador. Piscis debe aprender a comunicar sus sentimientos claramente en lugar de retirarse. Juntos, pueden inspirarse mutuamente a un nivel artístico y espiritual muy profundo.",
    score: 3
  }
};
    









