
import type { ZodiacSignName, Locale } from '@/types';

export interface CompatibilityReportDetail {
  report: Record<Locale, string>;
  score: number;
}

export const workCompatibilityPairings: Record<string, CompatibilityReportDetail> = {
  "Aries-Aries": {
    report: {
      es: "Un dúo de alta energía, ambición y una sana (a veces no tan sana) competitividad. Juntos, son una fuerza de la naturaleza para iniciar proyectos y tomar la iniciativa. Son excelentes para motivarse mutuamente y trabajar en entornos de ritmo rápido. Fortalezas: Rapidez, decisión y una valentía compartida. No temen a los desafíos. Desafíos: La lucha por el liderazgo es su mayor obstáculo. Ambos quieren estar al mando y pueden chocar si los roles no están claramente definidos. La impaciencia es otro problema; pueden apresurar las cosas sin planificar. Clave del éxito: Definir claramente quién lidera qué. Canalizar su espíritu competitivo hacia metas externas en lugar de entre ellos es fundamental.",
      en: "A duo of high energy, ambition, and a healthy (sometimes not so healthy) competitiveness. Together, they are a force of nature for initiating projects and taking the lead. They are excellent at motivating each other and working in fast-paced environments. Strengths: Speed, decision-making, and shared courage. They are not afraid of challenges. Challenges: The struggle for leadership is their biggest obstacle. Both want to be in charge and can clash if roles are not clearly defined. Impatience is another problem; they may rush things without planning. Key to success: Clearly defining who leads what. Channeling their competitive spirit towards external goals rather than each other is fundamental.",
      de: "Ein Duo mit hoher Energie, Ehrgeiz und einem gesunden (manchmal nicht so gesunden) Wettbewerbsgeist. Zusammen sind sie eine Naturgewalt, um Projekte zu initiieren und die Führung zu übernehmen. Sie sind hervorragend darin, sich gegenseitig zu motivieren und in schnelllebigen Umgebungen zu arbeiten. Stärken: Geschwindigkeit, Entscheidungsfindung und gemeinsamer Mut. Sie haben keine Angst vor Herausforderungen. Herausforderungen: Der Kampf um die Führung ist ihr größtes Hindernis. Beide wollen das Sagen haben und können aneinandergeraten, wenn die Rollen nicht klar definiert sind. Ungeduld ist ein weiteres Problem; sie können Dinge ohne Planung überstürzen. Schlüssel zum Erfolg: Klare Definition, wer was leitet. Ihren Wettbewerbsgeist auf externe Ziele zu richten anstatt aufeinander, ist grundlegend.",
      fr: "Un duo de haute énergie, d'ambition et d'une saine (parfois pas si saine) compétitivité. Ensemble, ils sont une force de la nature pour initier des projets et prendre les devants. Ils sont excellents pour se motiver mutuellement et travailler dans des environnements au rythme rapide. Forces : Rapidité, prise de décision et courage partagé. Ils n'ont pas peur des défis. Défis : La lutte pour le leadership est leur plus grand obstacle. Tous deux veulent être aux commandes et peuvent s'affronter si les rôles ne sont pas clairement définis. L'impatience est un autre problème ; ils peuvent précipiter les choses sans planifier. Clé du succès : Définir clairement qui dirige quoi. Canaliser leur esprit de compétition vers des objectifs externes plutôt que l'un contre l'autre est fondamental."
    },
    score: 3
  },
  "Aries-Taurus": {
    report: {
      es: "El velocista y el maratonista. Aries aporta la chispa inicial y la energía para empezar, mientras que Tauro proporciona la resistencia, la paciencia y el enfoque metódico para asegurar que el trabajo se haga bien y se complete. Esta colaboración puede ser la base de un negocio exitoso si aprenden a valorar sus dones únicos. Fortalezas: Si logran sincronizar sus ritmos, cubren todo el ciclo de un proyecto. Aries inicia y Tauro construye y finaliza. Desafíos: Sus ritmos son opuestos. Aries puede ver a Tauro como exasperantemente lento y adverso al riesgo, y Tauro puede ver a Aries como imprudente, descuidado y propenso a errores por la prisa. La frustración puede surgir si no se respetan mutuamente. Clave del éxito: Respeto absoluto por sus diferentes estilos. Aries debe aprender a valorar la calidad y la planificación de Tauro, y Tauro debe confiar en la visión y la iniciativa de Aries, dándole un voto de confianza para explorar.",
      en: "The sprinter and the marathoner. Aries brings the initial spark and energy to start, while Taurus provides the endurance, patience, and methodical approach to ensure the work is done well and completed. This collaboration can be the foundation of a successful business if they learn to value their unique gifts. Strengths: If they manage to synchronize their rhythms, they cover the entire project cycle. Aries initiates, and Taurus builds and finalizes. Challenges: Their rhythms are opposite. Aries may see Taurus as excruciatingly slow and risk-averse, and Taurus may see Aries as reckless, careless, and prone to mistakes due to haste. Frustration can arise if they do not respect each other. Key to success: Absolute respect for their different styles. Aries must learn to value Taurus's quality and planning, and Taurus must trust Aries's vision and initiative, giving it a vote of confidence to explore.",
      de: "Der Sprinter und der Marathonläufer. Widder bringt den anfänglichen Funken und die Energie zum Starten, während Stier die Ausdauer, Geduld und den methodischen Ansatz bietet, um sicherzustellen, dass die Arbeit gut und vollständig erledigt wird. Diese Zusammenarbeit kann die Grundlage für ein erfolgreiches Unternehmen sein, wenn sie lernen, ihre einzigartigen Gaben wertzuschätzen. Stärken: Wenn es ihnen gelingt, ihre Rhythmen zu synchronisieren, decken sie den gesamten Projektzyklus ab. Widder initiiert, und Stier baut und schließt ab. Herausforderungen: Ihre Rhythmen sind entgegengesetzt. Widder mag Stier als quälend langsam und risikoscheu ansehen, und Stier mag Widder als rücksichtslos, nachlässig und anfällig für Fehler aufgrund von Eile ansehen. Frustration kann entstehen, wenn sie sich nicht gegenseitig respektieren. Schlüssel zum Erfolg: Absoluter Respekt für ihre unterschiedlichen Stile. Widder muss lernen, die Qualität und Planung des Stiers zu schätzen, und Stier muss der Vision und Initiative des Widders vertrauen und ihm einen Vertrauensvorschuss zum Erkunden geben.",
      fr: "Le sprinteur et le marathonien. Le Bélier apporte l'étincelle initiale et l'énergie pour commencer, tandis que le Taureau fournit l'endurance, la patience et l'approche méthodique pour s'assurer que le travail est bien fait et terminé. Cette collaboration peut être la base d'une entreprise prospère s'ils apprennent à valoriser leurs dons uniques. Forces : S'ils parviennent à synchroniser leurs rythmes, ils couvrent l'ensemble du cycle du projet. Le Bélier initie, et le Taureau construit et finalise. Défis : Leurs rythmes sont opposés. Le Bélier peut voir le Taureau comme exaspérément lent et opposé au risque, et le Taureau peut voir le Bélier comme imprudent, négligent et sujet aux erreurs dues à la hâte. La frustration peut survenir s'ils ne se respectent pas mutuellement. Clé du succès : Un respect absolu pour leurs différents styles. Le Bélier doit apprendre à valoriser la qualité et la planification du Taureau, et le Taureau doit faire confiance à la vision et à l'initiative du Bélier, en lui donnant un vote de confiance pour explorer."
    },
    score: 3
  },
  "Aries-Gemini": {
    report: {
      es: "Un equipo creativo, dinámico y lleno de ideas. Aries es el motor que impulsa la acción, y Géminis es la mente brillante que genera múltiples opciones y estrategias de comunicación. Son una dupla fantástica para brainstorming, marketing, redes sociales y proyectos que requieren agilidad mental y ejecución rápida. Fortalezas: Energía inagotable, creatividad y una excelente capacidad para adaptarse a los cambios. Nunca se estancan y su ambiente de trabajo es divertido y estimulante. Desafíos: Ambos pueden carecer de constancia y seguimiento. Pueden saltar de una idea a otra sin terminar la anterior. La falta de atención a los detalles puede ser un problema recurrente que requiera supervisión externa. Clave del éxito: Designar a un tercero (o que uno de ellos asuma el rol, aunque les cueste) para que se encargue de la planificación detallada y el seguimiento, asegurando que sus brillantes ideas se materialicen.",
      en: "A creative, dynamic team full of ideas. Aries is the engine that drives action, and Gemini is the brilliant mind that generates multiple options and communication strategies. They are a fantastic duo for brainstorming, marketing, social media, and projects that require mental agility and quick execution. Strengths: Inexhaustible energy, creativity, and an excellent ability to adapt to changes. They never stagnate, and their work environment is fun and stimulating. Challenges: Both can lack consistency and follow-through. They can jump from one idea to another without finishing the previous one. Lack of attention to detail can be a recurring problem that requires external supervision. Key to success: Designating a third party (or one of them taking on the role, even if it's hard for them) to handle detailed planning and follow-up, ensuring their brilliant ideas materialize.",
      de: "Ein kreatives, dynamisches Team voller Ideen. Widder ist der Motor, der die Aktion antreibt, und Zwillinge ist der brillante Geist, der mehrere Optionen und Kommunikationsstrategien generiert. Sie sind ein fantastisches Duo für Brainstorming, Marketing, soziale Medien und Projekte, die geistige Beweglichkeit und schnelle Ausführung erfordern. Stärken: Unerschöpfliche Energie, Kreativität und eine ausgezeichnete Fähigkeit, sich an Veränderungen anzupassen. Sie stagnieren nie, und ihre Arbeitsumgebung ist unterhaltsam und anregend. Herausforderungen: Beiden kann es an Beständigkeit und Durchhaltevermögen mangeln. Sie können von einer Idee zur nächsten springen, ohne die vorherige zu beenden. Mangelnde Aufmerksamkeit für Details kann ein wiederkehrendes Problem sein, das externe Aufsicht erfordert. Schlüssel zum Erfolg: Die Benennung eines Dritten (oder einer von ihnen übernimmt die Rolle, auch wenn es ihnen schwerfällt), der sich um die detaillierte Planung und Nachverfolgung kümmert und sicherstellt, dass ihre brillanten Ideen verwirklicht werden.",
      fr: "Une équipe créative, dynamique et pleine d'idées. Le Bélier est le moteur qui anime l'action, et les Gémeaux sont l'esprit brillant qui génère de multiples options et stratégies de communication. Ils forment un duo fantastique pour le brainstorming, le marketing, les médias sociaux et les projets qui nécessitent une agilité mentale et une exécution rapide. Forces : Une énergie inépuisable, de la créativité et une excellente capacité à s'adapter aux changements. Ils ne stagnent jamais, et leur environnement de travail est amusant et stimulant. Défis : Tous deux peuvent manquer de constance et de suivi. Ils peuvent sauter d'une idée à l'autre sans terminer la précédente. Le manque d'attention aux détails peut être un problème récurrent qui nécessite une supervision externe. Clé du succès : Désigner un tiers (ou l'un d'eux endossant le rôle, même si c'est difficile pour eux) pour s'occuper de la planification détaillée et du suivi, en s'assurant que leurs brillantes idées se matérialisent."
    },
    score: 4
  },
  "Aries-Cancer": {
    report: {
      es: "Una combinación laboral delicada que requiere mucha conciencia emocional. La naturaleza directa y a veces abrasiva de Aries puede chocar fácilmente con la sensibilidad de Cáncer, quien puede tomarse las críticas como algo personal. Fortalezas: Aries puede motivar a Cáncer a salir de su zona de confort y a ser más asertivo. Cáncer puede enseñar a Aries la importancia de la intuición y el trabajo en equipo. Desafíos: La comunicación. Aries valora la franqueza, Cáncer la diplomacia. Los malentendidos son frecuentes si no se esfuerzan por comprender el estilo del otro. Clave del éxito: Aries debe aprender a ser un líder protector y no un jefe autoritario. Cáncer debe desarrollar una piel un poco más gruesa y comunicar sus necesidades de forma más directa.",
      en: "A delicate work combination that requires a lot of emotional awareness. Aries's direct and sometimes abrasive nature can easily clash with Cancer's sensitivity, who may take criticism personally. Strengths: Aries can motivate Cancer to step out of its comfort zone and be more assertive. Cancer can teach Aries the importance of intuition and teamwork. Challenges: Communication. Aries values frankness, Cancer values diplomacy. Misunderstandings are frequent if they do not strive to understand each other's style. Key to success: Aries must learn to be a protective leader and not an authoritarian boss. Cancer must develop a slightly thicker skin and communicate its needs more directly.",
      de: "Eine heikle Arbeitskombination, die viel emotionales Bewusstsein erfordert. Die direkte und manchmal abrasive Natur des Widders kann leicht mit der Sensibilität des Krebses kollidieren, der Kritik persönlich nehmen kann. Stärken: Widder kann den Krebs motivieren, seine Komfortzone zu verlassen und durchsetzungsfähiger zu sein. Krebs kann dem Widder die Bedeutung von Intuition und Teamarbeit beibringen. Herausforderungen: Kommunikation. Widder schätzt Offenheit, Krebs schätzt Diplomatie. Missverständnisse sind häufig, wenn sie sich nicht bemühen, den Stil des anderen zu verstehen. Schlüssel zum Erfolg: Widder muss lernen, ein schützender Führer und kein autoritärer Chef zu sein. Krebs muss eine etwas dickere Haut entwickeln und seine Bedürfnisse direkter kommunizieren.",
      fr: "Une combinaison de travail délicate qui demande beaucoup de conscience émotionnelle. La nature directe et parfois abrasive du Bélier peut facilement se heurter à la sensibilité du Cancer, qui peut prendre la critique personnellement. Forces : Le Bélier peut motiver le Cancer à sortir de sa zone de confort et à être plus affirmé. Le Cancer peut enseigner au Bélier l'importance de l'intuition et du travail d'équipe. Défis : La communication. Le Bélier apprécie la franchise, le Cancer la diplomatie. Les malentendus sont fréquents s'ils ne s'efforcent pas de comprendre le style de l'autre. Clé du succès : Le Bélier doit apprendre à être un leader protecteur et non un patron autoritaire. Le Cancer doit développer une peau un peu plus épaisse et communiquer ses besoins plus directement."
    },
    score: 2
  },
  "Aries-Leo": {
    report: {
      es: "El dúo dinámico del zodiaco. Dos signos de Fuego que se admiran, se respetan y se motivan mutuamente. Ambos son líderes natos, carismáticos y no temen tomar el centro del escenario. Juntos, pueden inspirar a todo un equipo. Fortalezas: Una ambición y energía compartidas. Son excelentes para ventas, marketing y roles de liderazgo. Se apoyan y celebran sus éxitos. Desafíos: La lucha de egos. Ambos quieren ser la estrella y pueden competir por el reconocimiento. Clave del éxito: Aprender a compartir el protagonismo y a funcionar como una 'power couple'. Si ven el éxito del otro como un éxito compartido, son verdaderamente imparables.",
      en: "The dynamic duo of the zodiac. Two Fire signs that admire, respect, and motivate each other. Both are natural leaders, charismatic, and are not afraid to take center stage. Together, they can inspire an entire team. Strengths: Shared ambition and energy. They are excellent for sales, marketing, and leadership roles. They support and celebrate each other's successes. Challenges: The clash of egos. Both want to be the star and can compete for recognition. Key to success: Learning to share the spotlight and function as a 'power couple'. If they see each other's success as a shared success, they are truly unstoppable.",
      de: "Das dynamische Duo des Tierkreises. Zwei Feuerzeichen, die sich gegenseitig bewundern, respektieren und motivieren. Beide sind geborene Führungskräfte, charismatisch und haben keine Angst, im Mittelpunkt zu stehen. Gemeinsam können sie ein ganzes Team inspirieren. Stärken: Geteilter Ehrgeiz und Energie. Sie sind hervorragend für Vertrieb, Marketing und Führungsrollen geeignet. Sie unterstützen und feiern die Erfolge des anderen. Herausforderungen: Der Kampf der Egos. Beide wollen der Star sein und können um Anerkennung konkurrieren. Schlüssel zum Erfolg: Lernen, das Rampenlicht zu teilen und als 'Power-Paar' zu funktionieren. Wenn sie den Erfolg des anderen als gemeinsamen Erfolg ansehen, sind sie wirklich unaufhaltsam.",
      fr: "Le duo dynamique du zodiaque. Deux signes de Feu qui s'admirent, se respectent et se motivent mutuellement. Tous deux sont des leaders nés, charismatiques, et n'ont pas peur de prendre le devant de la scène. Ensemble, ils peuvent inspirer toute une équipe. Forces : Une ambition et une énergie partagées. Ils sont excellents pour les ventes, le marketing et les rôles de leadership. Ils se soutiennent et célèbrent leurs succès mutuels. Défis : Le choc des ego. Tous deux veulent être la star et peuvent se disputer la reconnaissance. Clé du succès : Apprendre à partager la vedette et à fonctionner comme un 'couple de pouvoir'. S'ils voient le succès de l'autre comme un succès partagé, ils sont vraiment imparables."
    },
    score: 5
  },
  "Aries-Virgo": {
    report: {
      es: "El caos se encuentra con el orden. Aries es todo impulso y 'manos a la obra', mientras que Virgo es todo planificación, análisis y atención al detalle. Esta colaboración puede ser altamente productiva o un desastre de frustración. Fortalezas: Cubren todas las fases de un proyecto. Aries lo inicia con energía y Virgo lo perfecciona hasta el último detalle. Desafíos: Sus métodos son opuestos. Virgo se estresa con la falta de planificación de Aries, y Aries se impacienta con el meticuloso análisis de Virgo. Clave del éxito: Una delegación de tareas clara y un respeto absoluto por sus diferentes habilidades. Aries debe confiar en el proceso de Virgo, y Virgo debe confiar en la visión de Aries.",
      en: "Chaos meets order. Aries is all about impulse and 'getting things done', while Virgo is all about planning, analysis, and attention to detail. This collaboration can be highly productive or a disaster of frustration. Strengths: They cover all phases of a project. Aries starts it with energy, and Virgo perfects it down to the last detail. Challenges: Their methods are opposite. Virgo gets stressed by Aries's lack of planning, and Aries gets impatient with Virgo's meticulous analysis. Key to success: A clear delegation of tasks and absolute respect for their different skills. Aries must trust Virgo's process, and Virgo must trust Aries's vision.",
      de: "Chaos trifft auf Ordnung. Widder ist alles Impuls und 'Dinge erledigen', während Jungfrau alles Planung, Analyse und Liebe zum Detail ist. Diese Zusammenarbeit kann sehr produktiv oder eine Katastrophe der Frustration sein. Stärken: Sie decken alle Phasen eines Projekts ab. Widder startet es mit Energie, und Jungfrau perfektioniert es bis ins letzte Detail. Herausforderungen: Ihre Methoden sind gegensätzlich. Jungfrau wird durch die mangelnde Planung des Widders gestresst, und Widder wird ungeduldig mit der sorgfältigen Analyse der Jungfrau. Schlüssel zum Erfolg: Eine klare Aufgabenverteilung und absoluter Respekt für ihre unterschiedlichen Fähigkeiten. Widder muss dem Prozess der Jungfrau vertrauen, und Jungfrau muss der Vision des Widders vertrauen.",
      fr: "Le chaos rencontre l'ordre. Le Bélier est tout en impulsion et en 'action', tandis que la Vierge est tout en planification, analyse et attention aux détails. Cette collaboration peut être très productive ou un désastre de frustration. Forces : Ils couvrent toutes les phases d'un projet. Le Bélier le commence avec énergie, et la Vierge le perfectionne jusqu'au dernier détail. Défis : Leurs méthodes sont opposées. La Vierge est stressée par le manque de planification du Bélier, et le Bélier s'impatiente de l'analyse méticuleuse de la Vierge. Clé du succès : Une délégation claire des tâches et un respect absolu pour leurs différentes compétences. Le Bélier doit faire confiance au processus de la Vierge, et la Vierge doit faire confiance à la vision du Bélier."
    },
    score: 2
  },
  "Aries-Libra": {
    report: {
      es: "Una excelente combinación de 'músculo' y 'cerebro social'. Aries aporta la energía, la decisión y la acción directa, mientras que Libra aporta la estrategia, la diplomacia y la capacidad de construir puentes y negociar. Fortalezas: Se equilibran perfectamente. Son un equipo ideal para lanzar un nuevo producto o empresa, donde Aries impulsa el desarrollo y Libra gestiona las relaciones públicas y las alianzas. Desafíos: La aversión de Libra al conflicto puede chocar con la naturaleza confrontacional de Aries. Libra puede tardar en decidir, frustrando al impaciente Aries. Clave del éxito: Libra debe aprender a ser más directo, y Aries a valorar la diplomacia. Juntos, son la combinación perfecta de acción y estrategia.",
      en: "An excellent combination of 'muscle' and 'social brain'. Aries brings energy, decision-making, and direct action, while Libra brings strategy, diplomacy, and the ability to build bridges and negotiate. Strengths: They balance each other perfectly. They are an ideal team for launching a new product or company, where Aries drives development and Libra manages public relations and alliances. Challenges: Libra's aversion to conflict can clash with Aries's confrontational nature. Libra can be slow to decide, frustrating the impatient Aries. Key to success: Libra must learn to be more direct, and Aries to value diplomacy. Together, they are the perfect combination of action and strategy.",
      de: "Eine ausgezeichnete Kombination aus 'Muskeln' und 'sozialem Gehirn'. Widder bringt Energie, Entscheidungsfindung und direkte Aktion, während Waage Strategie, Diplomatie und die Fähigkeit, Brücken zu bauen und zu verhandeln, mitbringt. Stärken: Sie gleichen sich perfekt aus. Sie sind ein ideales Team für die Einführung eines neuen Produkts oder Unternehmens, bei dem Widder die Entwicklung vorantreibt und Waage die Öffentlichkeitsarbeit und Allianzen managt. Herausforderungen: Die Abneigung der Waage gegen Konflikte kann mit der konfrontativen Natur des Widders kollidieren. Waage kann langsam bei Entscheidungen sein, was den ungeduldigen Widder frustriert. Schlüssel zum Erfolg: Waage muss lernen, direkter zu sein, und Widder, Diplomatie zu schätzen. Zusammen sind sie die perfekte Kombination aus Aktion und Strategie.",
      fr: "Une excellente combinaison de 'muscle' et de 'cerveau social'. Le Bélier apporte l'énergie, la prise de décision et l'action directe, tandis que la Balance apporte la stratégie, la diplomatie et la capacité de construire des ponts et de négocier. Forces : Ils s'équilibrent parfaitement. Ils forment une équipe idéale pour lancer un nouveau produit ou une nouvelle entreprise, où le Bélier pilote le développement et la Balance gère les relations publiques et les alliances. Défis : L'aversion de la Balance pour les conflits peut se heurter à la nature conflictuelle du Bélier. La Balance peut être lente à décider, frustrant le Bélier impatient. Clé du succès : La Balance doit apprendre à être plus directe, et le Bélier à valoriser la diplomatie. Ensemble, ils sont la combinaison parfaite d'action et de stratégie."
    },
    score: 4
  },
  "Aries-Scorpio": {
    report: {
      es: "Dos guerreros regidos por Marte en el mismo campo de batalla. La intensidad, la pasión y la determinación son enormes. Son un equipo formidable en situaciones de alta presión o crisis, donde su valentía combinada brilla. Fortalezas: Ambición, resiliencia y una capacidad para ir hasta el final. No se rinden fácilmente. Desafíos: Las luchas de poder son casi una garantía. Ambos son dominantes y quieren tener el control. La desconfianza puede surgir si no son completamente transparentes. Clave del éxito: La confianza y el respeto mutuo son innegociables. Deben tener roles muy bien definidos y aprender a canalizar su intensidad hacia metas comunes, en lugar de competir entre ellos.",
      en: "Two warriors ruled by Mars on the same battlefield. The intensity, passion, and determination are enormous. They are a formidable team in high-pressure or crisis situations, where their combined courage shines. Strengths: Ambition, resilience, and an ability to go all the way. They do not give up easily. Challenges: Power struggles are almost a guarantee. Both are dominant and want to be in control. Mistrust can arise if they are not completely transparent. Key to success: Trust and mutual respect are non-negotiable. They must have very well-defined roles and learn to channel their intensity towards common goals, rather than competing with each other.",
      de: "Zwei von Mars regierte Krieger auf demselben Schlachtfeld. Die Intensität, Leidenschaft und Entschlossenheit sind enorm. Sie sind ein beeindruckendes Team in Hochdruck- oder Krisensituationen, in denen ihr gemeinsamer Mut glänzt. Stärken: Ehrgeiz, Belastbarkeit und die Fähigkeit, bis zum Ende zu gehen. Sie geben nicht leicht auf. Herausforderungen: Machtkämpfe sind fast eine Garantie. Beide sind dominant und wollen die Kontrolle haben. Misstrauen kann aufkommen, wenn sie nicht vollständig transparent sind. Schlüssel zum Erfolg: Vertrauen und gegenseitiger Respekt sind nicht verhandelbar. Sie müssen sehr klar definierte Rollen haben und lernen, ihre Intensität auf gemeinsame Ziele zu lenken, anstatt miteinander zu konkurrieren.",
      fr: "Deux guerriers gouvernés par Mars sur le même champ de bataille. L'intensité, la passion et la détermination sont énormes. Ils forment une équipe redoutable dans les situations de haute pression ou de crise, où leur courage combiné brille. Forces : L'ambition, la résilience et la capacité d'aller jusqu'au bout. Ils n'abandonnent pas facilement. Défis : Les luttes de pouvoir sont presque une garantie. Tous deux sont dominants et veulent avoir le contrôle. La méfiance peut survenir s'ils ne sont pas complètement transparents. Clé du succès : La confiance et le respect mutuel sont non négociables. Ils doivent avoir des rôles très bien définis et apprendre à canaliser leur intensité vers des objectifs communs, plutôt que de se faire concurrence."
    },
    score: 3
  },
  "Aries-Sagittarius": {
    report: {
      es: "El equipo de Fuego de los pioneros. Dinámicos, optimistas y siempre en busca de la próxima gran aventura. Son excelentes para explorar nuevos mercados, lanzar ideas innovadoras y mantener la moral del equipo por las nubes. Fortalezas: Una energía y entusiasmo contagiosos. Se entienden en su necesidad de libertad y no temen tomar riesgos calculados. Desafíos: La falta de atención a los detalles y la planificación a largo plazo. Pueden ser geniales para empezar, pero necesitan a alguien que se ocupe del seguimiento y la ejecución detallada. Clave del éxito: Equilibrar su visión con un plan práctico. Disfrutar del viaje mientras mantienen el ojo en el destino final.",
      en: "The Fire team of pioneers. Dynamic, optimistic, and always looking for the next great adventure. They are excellent for exploring new markets, launching innovative ideas, and keeping team morale high. Strengths: Contagious energy and enthusiasm. They understand each other's need for freedom and are not afraid to take calculated risks. Challenges: Lack of attention to detail and long-term planning. They can be great at starting, but they need someone to handle the follow-up and detailed execution. Key to success: Balancing their vision with a practical plan. Enjoying the journey while keeping an eye on the final destination.",
      de: "Das Feuer-Team der Pioniere. Dynamisch, optimistisch und immer auf der Suche nach dem nächsten großen Abenteuer. Sie eignen sich hervorragend, um neue Märkte zu erkunden, innovative Ideen zu lancieren und die Team-Moral hoch zu halten. Stärken: Ansteckende Energie und Begeisterung. Sie verstehen das Bedürfnis des anderen nach Freiheit und haben keine Angst, kalkulierte Risiken einzugehen. Herausforderungen: Mangelnde Aufmerksamkeit für Details und langfristige Planung. Sie können großartig im Anfangen sein, brauchen aber jemanden, der sich um die Nachverfolgung und die detaillierte Ausführung kümmert. Schlüssel zum Erfolg: Ihre Vision mit einem praktischen Plan in Einklang zu bringen. Die Reise genießen und dabei das Endziel im Auge behalten.",
      fr: "L'équipe de Feu des pionniers. Dynamiques, optimistes et toujours à la recherche de la prochaine grande aventure. Ils sont excellents pour explorer de nouveaux marchés, lancer des idées novatrices et maintenir le moral de l'équipe au plus haut. Forces : Une énergie et un enthousiasme contagieux. Ils se comprennent dans leur besoin de liberté et n'ont pas peur de prendre des risques calculés. Défis : Le manque d'attention aux détails et la planification à long terme. Ils peuvent être excellents pour commencer, mais ils ont besoin de quelqu'un pour s'occuper du suivi et de l'exécution détaillée. Clé du succès : Équilibrer leur vision avec un plan pratique. Profiter du voyage tout en gardant un œil sur la destination finale."
    },
    score: 4
  },
  "Aries-Capricorn": {
    report: {
      es: "El impulso se encuentra con la estrategia. Aries es el cohete que quiere despegar ya, y Capricornio es la torre de control que planifica la trayectoria hasta el último detalle. Es una combinación de respeto mutuo si logran superar sus diferencias de ritmo. Fortalezas: Aries aporta la energía para la innovación y la acción rápida, mientras que Capricornio aporta la disciplina y la visión a largo plazo para construir algo duradero y exitoso. Desafíos: La impaciencia de Aries choca con la cautela de Capricornio. Aries puede ver a Capricornio como un freno, y Capricornio a Aries como imprudente. Clave del éxito: La paciencia. Capricornio debe valorar la capacidad de Aries para iniciar, y Aries debe respetar la sabiduría y la planificación estratégica de Capricornio. Juntos, pueden conquistar cualquier cima.",
      en: "Impulse meets strategy. Aries is the rocket that wants to take off now, and Capricorn is the control tower that plans the trajectory down to the last detail. It's a combination of mutual respect if they can overcome their differences in pace. Strengths: Aries brings the energy for innovation and quick action, while Capricorn brings the discipline and long-term vision to build something lasting and successful. Challenges: Aries's impatience clashes with Capricorn's caution. Aries may see Capricorn as a brake, and Capricorn may see Aries as reckless. Key to success: Patience. Capricorn must value Aries's ability to initiate, and Aries must respect Capricorn's wisdom and strategic planning. Together, they can conquer any peak.",
      de: "Impuls trifft auf Strategie. Widder ist die Rakete, die jetzt starten will, und Steinbock ist der Kontrollturm, der die Flugbahn bis ins letzte Detail plant. Es ist eine Kombination aus gegenseitigem Respekt, wenn sie ihre Unterschiede im Tempo überwinden können. Stärken: Widder bringt die Energie für Innovation und schnelles Handeln, während Steinbock die Disziplin und langfristige Vision mitbringt, um etwas Dauerhaftes und Erfolgreiches aufzubauen. Herausforderungen: Die Ungeduld des Widders kollidiert mit der Vorsicht des Steinbocks. Widder mag Steinbock als Bremse ansehen, und Steinbock mag Widder als rücksichtslos ansehen. Schlüssel zum Erfolg: Geduld. Steinbock muss die Fähigkeit des Widders schätzen, zu initiieren, und Widder muss die Weisheit und strategische Planung des Steinbocks respektieren. Zusammen können sie jeden Gipfel erobern.",
      fr: "L'impulsion rencontre la stratégie. Le Bélier est la fusée qui veut décoller maintenant, et le Capricorne est la tour de contrôle qui planifie la trajectoire jusqu'au dernier détail. C'est une combinaison de respect mutuel s'ils peuvent surmonter leurs différences de rythme. Forces : Le Bélier apporte l'énergie pour l'innovation et l'action rapide, tandis que le Capricorne apporte la discipline et la vision à long terme pour construire quelque chose de durable et de réussi. Défis : L'impatience du Bélier se heurte à la prudence du Capricorne. Le Bélier peut voir le Capricorne comme un frein, et le Capricorne peut voir le Bélier comme imprudent. Clé du succès : La patience. Le Capricorne doit valoriser la capacité du Bélier à initier, et le Bélier doit respecter la sagesse et la planification stratégique du Capricorne. Ensemble, ils peuvent conquérir n'importe quel sommet."
    },
    score: 3
  },
  "Aries-Aquarius": {
    report: {
      es: "El inventor y el emprendedor. Acuario tiene las ideas geniales, originales y a menudo revolucionarias, y Aries tiene el coraje, la energía y el impulso para llevarlas al mercado. Son una pareja ideal para startups, tecnología y cualquier campo que requiera innovación. Fortalezas: Una combinación de visión de futuro y acción presente. Ambos son independientes y respetan la libertad del otro. Desafíos: La conexión emocional puede ser débil. Acuario puede ser demasiado desapegado para el apasionado Aries. La ejecución de los detalles puede no ser el fuerte de ninguno de los dos. Clave del éxito: Trabajar en proyectos que les apasionen a ambos. Celebrar la originalidad del otro y encontrar a alguien que se ocupe de la gestión del día a día.",
      en: "The inventor and the entrepreneur. Aquarius has the brilliant, original, and often revolutionary ideas, and Aries has the courage, energy, and drive to bring them to market. They are an ideal pair for startups, technology, and any field that requires innovation. Strengths: A combination of future vision and present action. Both are independent and respect each other's freedom. Challenges: The emotional connection can be weak. Aquarius can be too detached for the passionate Aries. The execution of details may not be the strong suit of either. Key to success: Working on projects that they are both passionate about. Celebrating each other's originality and finding someone to handle the day-to-day management.",
      de: "Der Erfinder und der Unternehmer. Wassermann hat die brillanten, originellen und oft revolutionären Ideen, und Widder hat den Mut, die Energie und den Antrieb, sie auf den Markt zu bringen. Sie sind ein ideales Paar für Start-ups, Technologie und jedes Feld, das Innovation erfordert. Stärken: Eine Kombination aus Zukunftsvision und gegenwärtiger Aktion. Beide sind unabhängig und respektieren die Freiheit des anderen. Herausforderungen: Die emotionale Verbindung kann schwach sein. Wassermann kann für den leidenschaftlichen Widder zu distanziert sein. Die Ausführung von Details ist möglicherweise nicht die Stärke von beiden. Schlüssel zum Erfolg: An Projekten arbeiten, für die sie beide eine Leidenschaft haben. Die Originalität des anderen feiern und jemanden finden, der sich um das Tagesgeschäft kümmert.",
      fr: "L'inventeur et l'entrepreneur. Le Verseau a les idées brillantes, originales et souvent révolutionnaires, et le Bélier a le courage, l'énergie et la volonté de les commercialiser. Ils forment une paire idéale pour les startups, la technologie et tout domaine qui nécessite de l'innovation. Forces : Une combinaison de vision d'avenir et d'action présente. Tous deux sont indépendants et respectent la liberté de l'autre. Défis : La connexion émotionnelle peut être faible. Le Verseau peut être trop détaché pour le Bélier passionné. L'exécution des détails n'est peut-être le point fort d'aucun des deux. Clé du succès : Travailler sur des projets qui les passionnent tous les deux. Célébrer l'originalité de l'autre et trouver quelqu'un pour s'occuper de la gestion quotidienne."
    },
    score: 4
  },
  "Aries-Pisces": {
    report: {
      es: "El líder y el visionario creativo. Aries puede proporcionar la estructura, la dirección y la confianza que el soñador Piscis a menudo necesita para concretar sus ideas. A su vez, Piscis puede aportar una perspectiva intuitiva y una creatividad sin límites que inspira a Aries. Fortalezas: Piscis puede visualizar el producto final, y Aries puede trazar el camino para llegar allí. Juntos, son excelentes en campos artísticos, publicitarios o de ayuda social. Desafíos: La comunicación debe ser delicada. La franqueza de Aries puede herir la sensibilidad de Piscis. La tendencia de Piscis a ser evasivo puede frustrar al directo Aries. Clave del éxito: Aries debe actuar como un líder protector, no como un sargento. Piscis debe hacer un esfuerzo por ser más claro y directo en sus comunicaciones.",
      en: "The leader and the creative visionary. Aries can provide the structure, direction, and confidence that the dreamy Pisces often needs to realize its ideas. In turn, Pisces can bring an intuitive perspective and limitless creativity that inspires Aries. Strengths: Pisces can visualize the final product, and Aries can map the path to get there. Together, they are excellent in artistic, advertising, or social aid fields. Challenges: Communication must be delicate. Aries's frankness can hurt Pisces's sensitivity. Pisces's evasive tendency can frustrate the direct Aries. Key to success: Aries must act as a protective leader, not a sergeant. Pisces must make an effort to be clearer and more direct in its communications.",
      de: "Der Führer und der kreative Visionär. Widder kann die Struktur, Richtung und das Vertrauen bieten, die die träumerischen Fische oft brauchen, um ihre Ideen zu verwirklichen. Im Gegenzug können Fische eine intuitive Perspektive und grenzenlose Kreativität einbringen, die den Widder inspirieren. Stärken: Fische können das Endprodukt visualisieren, und Widder kann den Weg dorthin aufzeigen. Zusammen sind sie hervorragend in künstlerischen, werblichen oder sozialen Bereichen. Herausforderungen: Die Kommunikation muss heikel sein. Die Offenheit des Widders kann die Sensibilität der Fische verletzen. Die ausweichende Tendenz der Fische kann den direkten Widder frustrieren. Schlüssel zum Erfolg: Widder muss als schützender Führer agieren, nicht als Feldwebel. Fische müssen sich bemühen, in ihrer Kommunikation klarer und direkter zu sein.",
      fr: "Le leader et le visionnaire créatif. Le Bélier peut fournir la structure, la direction et la confiance dont les Poissons rêveurs ont souvent besoin pour concrétiser leurs idées. À leur tour, les Poissons peuvent apporter une perspective intuitive et une créativité sans limites qui inspirent le Bélier. Forces : Les Poissons peuvent visualiser le produit final, et le Bélier peut tracer le chemin pour y parvenir. Ensemble, ils sont excellents dans les domaines artistiques, publicitaires ou d'aide sociale. Défis : La communication doit être délicate. La franchise du Bélier peut blesser la sensibilité des Poissons. La tendance évasive des Poissons peut frustrer le Bélier direct. Clé du succès : Le Bélier doit agir comme un leader protecteur, pas comme un sergent. Les Poissons doivent faire un effort pour être plus clairs et plus directs dans leurs communications."
    },
    score: 3
  }
};
