
export interface Psychic {
  id: string;
  name: string;
  image: string;
  specialty: string; // Translation key
  phrase: string; // Translation key
  rating: number;
  reviews: number;
  experience: number; // years
  price: number | null; // null if free
  isFree: boolean;
  status: "Available" | "Busy" | "Meditating";
  aiHint: string;
}

export const psychics: Psychic[] = [
  {
    id: 'shenaya',
    name: 'Shenaya',
    image: 'https://placehold.co/200x200.png',
    aiHint: 'woman portrait confident',
    specialty: 'PsychicSpecialty.loveRelationships',
    phrase: 'PsychicPhrase.esmeralda',
    rating: 4.8,
    reviews: 207,
    experience: 9,
    price: null,
    isFree: true,
    status: 'Available',
  },
  {
    id: 'missmia',
    name: 'Miss Mia',
    image: 'https://placehold.co/200x200.png',
    aiHint: 'woman portrait friendly',
    specialty: 'PsychicSpecialty.careerFinance',
    phrase: 'PsychicPhrase.zephyr',
    rating: 4.5,
    reviews: 60,
    experience: 11,
    price: 3.99,
    isFree: false,
    status: 'Available',
  },
  {
    id: 'seraphina',
    name: 'Seraphina',
    image: 'https://placehold.co/200x200.png',
    aiHint: 'woman portrait ethereal',
    specialty: 'PsychicSpecialty.spiritualityGrowth',
    phrase: 'PsychicPhrase.seraphina',
    rating: 4.9,
    reviews: 1520,
    experience: 15,
    price: 5.50,
    isFree: false,
    status: 'Busy',
  },
  {
    id: 'aurora',
    name: 'Aurora',
    image: 'https://placehold.co/200x200.png',
    aiHint: 'woman portrait mystical',
    specialty: 'PsychicSpecialty.loveRelationships',
    phrase: 'PsychicPhrase.aurora',
    rating: 4.7,
    reviews: 834,
    experience: 12,
    price: 4.50,
    isFree: false,
    status: 'Available',
  },
  {
    id: 'orion',
    name: 'Orion',
    image: 'https://placehold.co/200x200.png',
    aiHint: 'man portrait wise',
    specialty: 'PsychicSpecialty.careerFinance',
    phrase: 'PsychicPhrase.orion',
    rating: 4.6,
    reviews: 512,
    experience: 7,
    price: null,
    isFree: true,
    status: 'Meditating',
  },
  {
    id: 'luna',
    name: 'Luna',
    image: 'https://placehold.co/200x200.png',
    aiHint: 'woman portrait gentle',
    specialty: 'PsychicSpecialty.spiritualityGrowth',
    phrase: 'PsychicPhrase.seraphina',
    rating: 4.8,
    reviews: 987,
    experience: 10,
    price: 4.99,
    isFree: false,
    status: 'Available',
  },
  {
    id: 'kaelen',
    name: 'Kaelen',
    image: 'https://placehold.co/200x200.png',
    aiHint: 'man portrait serene',
    specialty: 'PsychicSpecialty.spiritualityGrowth',
    phrase: 'PsychicPhrase.kaelen',
    rating: 4.9,
    reviews: 450,
    experience: 20,
    price: null,
    isFree: true,
    status: 'Meditating',
  },
  {
    id: 'isolde',
    name: 'Isolde',
    image: 'https://placehold.co/200x200.png',
    aiHint: 'woman portrait romantic',
    specialty: 'PsychicSpecialty.loveRelationships',
    phrase: 'PsychicPhrase.isolde',
    rating: 4.7,
    reviews: 1120,
    experience: 8,
    price: 6.99,
    isFree: false,
    status: 'Available',
  },
  {
    id: 'rohan',
    name: 'Rohan',
    image: 'https://placehold.co/200x200.png',
    aiHint: 'man portrait sharp business',
    specialty: 'PsychicSpecialty.careerFinance',
    phrase: 'PsychicPhrase.rohan',
    rating: 4.8,
    reviews: 780,
    experience: 13,
    price: 5.99,
    isFree: false,
    status: 'Busy',
  },
  {
    id: 'lyra',
    name: 'Lyra',
    image: 'https://placehold.co/200x200.png',
    aiHint: 'woman portrait vibrant musical',
    specialty: 'PsychicSpecialty.generalReading',
    phrase: 'PsychicPhrase.lyra',
    rating: 4.6,
    reviews: 310,
    experience: 5,
    price: null,
    isFree: true,
    status: 'Available',
  },
];
